UNSTACKABLES = [
    "wooden_axe",
    "golden_axe",
    "stone_axe",
    "iron_axe",
    "diamond_axe",
    "netherite_axe",
    "wooden_sword",
    "golden_sword",
    "stone_sword",
    "iron_sword",
    "diamond_sword",
    "netherite_sword",
    "wooden_pickaxe",
    "golden_pickaxe",
    "stone_pickaxe",
    "iron_pickaxe",
    "diamond_pickaxe",
    "netherite_pickaxe",
    "wooden_shovel",
    "golden_shovel",
    "stone_shovel",
    "iron_shovel",
    "diamond_shovel",
    "netherite_shovel",
    "wooden_hoe",
    "golden_hoe",
    "stone_hoe",
    "iron_hoe",
    "diamond_hoe",
    "netherite_hoe",

    "guster_banner_pattern",
    "mojang_banner_pattern",
    "piglin_banner_pattern",
    "skull_banner_pattern",
    "banner_pattern",
    "bordure_indented_banner_pattern",
    "creeper_banner_pattern",
    "field_masoned_banner_pattern",
    "flow_banner_pattern",
    "flower_banner_pattern",
    "globe_banner_pattern",

    "black_bed",
    "gray_bed",
    "light_gray_bed",
    "brown_bed",
    "red_bed",
    "orange_bed",
    "yellow_bed",
    "lime_bed",
    "green_bed",
    "cyan_bed",
    "blue_bed",
    "light_blue_bed",
    "pink_bed",
    "magenta_bed",
    "purple_bed",
    "white_bed",

    "beetroot_soup",
    "book_and_quill",

    "birch_boat",
    "cherry_boat",
    "acacia_boat",
    "oak_boat",
    "dark_oak_boat",
    "pale_oak_boat",
    "jungle_boat",
    "mangrove_boat",
    "spruce_boat",
    "birch_chest_boat",
    "cherry_chest_boat",
    "acacia_chest_boat",
    "oak_chest_boat",
    "dark_oak_chest_boat",
    "pale_oak_chest_boat",
    "jungle_chest_boat",
    "mangrove_chest_boat",
    "spruce_chest_boat",

    "leather_boots",
    "chainmail_boots",
    "golden_boots",
    "iron_boots",
    "diamond_boots",
    "netherite_boots",
    "leather_pants",
    "chainmail_leggings",
    "golden_leggings",
    "iron_leggings",
    "diamond_leggings",
    "netherite_leggings",
    "leather_tunic",
    "chainmail_chestplate",
    "golden_chestplate",
    "iron_chestplate",
    "diamond_chestplate",
    "netherite_chestplate",
    "leather_hat",
    "chainmail_helmet",
    "golden_helmet",
    "iron_helmet",
    "diamond_helmet",
    "netherite_helmet",

    "bow",
    "brush",

    "cod_bucket",
    "axolotl_bucket",
    "pufferfish_bucket",
    "salmon_bucket",
    "tadpole_bucket",
    "tropical_fish_bucket",
    "water_bucket",
    "lava_bucket",
    "milk_bucket",
    "powder_snow_bucket",

    "bundle",
    "black_bundle",
    "gray_bundle",
    "light_gray_bundle",
    "brown_bundle",
    "red_bundle",
    "orange_bundle",
    "yellow_bundle",
    "lime_bundle",
    "green_bundle",
    "cyan_bundle",
    "blue_bundle",
    "light_blue_bundle",
    "pink_bundle",
    "magenta_bundle",
    "purple_bundle",
    "white_bundle",

    "carrot_on_a_stick",
    "crossbow",
    "elytra",
    "enchanted_book",
    "fishing_rod",
    "flint_and_steel",
    "goat_horn",

    "leather_horse_armor",
    "iron_horse_armor",
    "golden_horse_armor",
    "diamond_horse_armor",

    "potion",
    "lingering_potion",
    "splash_potion",

    "mace",

    "minecart",
    "chest_minecart",
    "furnace_minecart",
    "hopper_minecart",
    "tnt_minecart",

    "mushroom_stew",

    "music_disc_5",
    "music_disc_11",
    "music_disc_13",
    "music_disc_blocks",
    "music_disc_cat",
    "music_disc_chirp",
    "music_disc_creator",
    "music_disc_creator_music_box",
    "music_disc_far",
    "music_disc_mall",
    "music_disc_mellohi",
    "music_disc_otherside",
    "music_disc_pigstep",
    "music_disc_precipice",
    "music_disc_relic",
    "music_disc_stal",
    "music_disc_strad",
    "music_disc_wait",
    "music_disc_ward",

    "rabbit_stew",
    "saddle",
    "shield",
    "shears",

    "shulker_box",
    "black_shulker_box",
    "gray_shulker_box",
    "light_gray_shulker_box",
    "brown_shulker_box",
    "red_shulker_box",
    "orange_shulker_box",
    "yellow_shulker_box",
    "lime_shulker_box",
    "green_shulker_box",
    "cyan_shulker_box",
    "blue_shulker_box",
    "light_blue_shulker_box",
    "pink_shulker_box",
    "magenta_shulker_box",
    "purple_shulker_box",
    "white_shulker_box",

    "spyglass",
    "suspicious_stew",
    "totem_of_undying",
    "trident",
    "turtle_shell",
    "warped_fungus_on_a_stick",
    "wolf_armor"
]

QUARTER_STACKABLES = [

]